### PR TITLE
Generalize methods to use MonadIO class, and bracket exceptions in the computation.

### PR DESCRIPTION
**Pull request by bairyn**
This change cleans up old resources if the computation throws an exception.

### CODE REVIEW

**Comment by ezyang** [comment]
If it were up to me, I'd veto any MonadCatchIO stuff. It is not going to work with the upcoming 7.8 release.

In the sub-patch, why doesn't outHandle also need to be closed upon failure? Switching everything to use brackets seems best.

**Comment by liyang** [comment]
Agreed, `MonadCatchIO-transformers` is a bad idea.

I've added a second patch ba608e35506f5f30fe17913eb13589840f9f0118 (on top of 6b35e936a8576e5d99b005d0e5f198501733a3c2; rebased and force-pushed) that makes sure `outHandle` is closed. It's a bit awkward in that `outHandle` (wrapping `rfd`) can't be closed until after we've done the `takeMVar`, so it's not just two nested `bracket`s.

@bairyn If the [`finally-cleanup`](https://github.com/liyang/system-posix-redirect/tree/finally-cleanup) branch looks good enough, let me know and I'll do a release.

**Comment by liyang** [comment]
Sorry, rebased again to include ticket number in commit message.

**Comment by liyang** [comment]
Okay, no one's responding, so I'm just going to merge it in and do a release. Have checked with:

``` diff
diff --git i/System/Posix/Redirect.hs w/System/Posix/Redirect.hs
index b75f4d2..3a038ef 100644
--- i/System/Posix/Redirect.hs
+++ w/System/Posix/Redirect.hs
@@ -76,6 +76,16 @@ unsafeRedirectWriteFd fd f = bracket setup (hClose . fst) $
         outHandle <- fdToHandle rfd
         return (outHandle, (wfd, old))

+    hClose h = do
+        System.IO.hPutStrLn stderr $ "hClose " ++ show h
+        System.IO.hFlush stderr
+        System.IO.hClose h
+
+    closeFd h = do
+        System.IO.hPutStrLn stderr $ "closeFd " ++ show h
+        System.IO.hFlush stderr
+        System.Posix.IO.closeFd h
+
 -- | @'redirectWriteHandle' oldFd oldHandle oldCHandle f@ executes the
 -- computation @f@, passing as an argument a handle which is the read
 -- end of a pipe that @fd@ now points to.  This function appropriately
```

and I got with `cabal repl`:

``` haskell
*> redirectStdout (System.IO.putStr "foo" >> error "no")
closeFd 9
hClose {handle: <file descriptor: 8>}
*** Exception: no
*> 
```

Prior to the above patches, the FD and Handle numbers would increase with repeated calls to `redirectStdout`, confirming that they were not being closed; that no longer happens.

**Pull request closed without merging**
